# Generated by Django 5.1.4 on 2025-01-05 05:22

import Myapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloodType', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default='A+', max_length=3)),
                ('Qantity', models.IntegerField(help_text='Quantity of Blood available')),
            ],
            options={
                'verbose_name_plural': 'Blood',
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CylinderType', models.CharField(help_text='Type of Cylinder (e.g., Oxygen)', max_length=50)),
                ('Quantity', models.IntegerField(help_text='Quantity of Cylinders available')),
            ],
            options={
                'verbose_name_plural': 'Cylinder',
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonatorName', models.CharField(max_length=50)),
                ('DonarBloodType', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default='A+', max_length=3)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=' ', max_length=7)),
                ('Status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='', max_length=6)),
                ('OrganAvailable', models.CharField(default=' ', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Organ',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.CharField(help_text='Hospital Name', max_length=50, unique=True)),
                ('Admin', models.CharField(help_text='Hospital Admin', max_length=50)),
                ('Address', models.TextField(help_text='Hospital Address', max_length=100)),
                ('Pincode', models.CharField(max_length=6, validators=[Myapp.models.pincode_validator])),
                ('PhoneNumber', models.CharField(help_text='Hospital Number', max_length=13)),
                ('AvailableDoctors', models.IntegerField(max_length=3)),
                ('Is_Active', models.BooleanField(default=True)),
                ('blood_types', models.ManyToManyField(related_name='hospitals', to='Myapp.blood')),
                ('cylinders', models.ManyToManyField(related_name='hospitals', to='Myapp.cylinder')),
                ('organs', models.ManyToManyField(related_name='hospitals', to='Myapp.organ')),
            ],
            options={
                'verbose_name_plural': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(help_text='Doctor Name', max_length=50, unique=True)),
                ('Doc_PhoneNumber', models.CharField(help_text='Doctor Number', max_length=13)),
                ('Specialization', models.CharField(max_length=40)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctors', to='Myapp.hospital')),
            ],
            options={
                'verbose_name_plural': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ambulance_count', models.IntegerField(blank=True, help_text='Number of Ambulances available', null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Myapp.hospital')),
            ],
            options={
                'verbose_name_plural': 'Availability',
            },
        ),
    ]
