# Generated by Django 5.1.4 on 2025-01-22 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(help_text='Patient Name', max_length=50)),
                ('Age', models.CharField(help_text='Patient Name', max_length=3)),
                ('Description', models.TextField(help_text='Patient Description')),
                ('date', models.DateField()),
                ('HospitalName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='Myapp.hospital')),
            ],
        ),
    ]
