# Generated by Django 5.1.4 on 2025-01-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='AvailableDoctors',
            field=models.IntegerField(),
        ),
    ]
