# Generated by Django 5.1.4 on 2025-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_hospital_availabledoctors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'Appointment'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Age',
            field=models.CharField(help_text='Patient Age', max_length=3),
        ),
    ]
